Make cache type less strict
evansiroky/node-geo-tz pull request #179
Opened 2024-09-30 10:47 UTC by klzns

I'm using `mnemonist/lru-map` to store the cache in my node project, like so:

```ts
import { find, setCache } from 'geo-tz/dist/find-all';
import LRUMap from 'mnemonist/lru-map';

// geo-tz can hold a total of 21,000 items in memory, costing 1.5GB when full
// The LRUMap of 5,000 items limits its size to ~400MB
const cacheStore = new LRUMap(5000);

// We need to type-cast because the expected type is a Map
// but it only expects a map-like entity with get and set methods
setCache({ store: cacheStore as unknown as Map<string, any> });
```

I would like to remove this type-casting, so I created this PR to relax the cache type to something that accepts another map-like entities like the `LRUMap`.

After the changes introduced by this PR, my code looks like this instead:

```ts
import { find, setCache } from 'geo-tz/dist/find-all';
import LRUMap from 'mnemonist/lru-map';

// geo-tz can hold a total of 21,000 items in memory, costing 1.5GB when full
// The LRUMap of 5,000 items limits its size to ~400MB
const cacheStore = new LRUMap(5000);

setCache({ store: cacheStore });
```

2024-10-01 21:16 UTC, evansiroky requested changes
The code seems good to me, but please revise your commits to use [Conventional Commits](https://www.conventionalcommits.org/).

2024-10-07 15:34 UTC, klzns commented
@evansiroky ops, fixed!

2024-10-08 17:07 UTC, evansiroky approved these changes

2024-10-08 17:08 UTC, merged

2024-10-08 17:12 UTC, evansiroky commented
:tada: This PR is included in version 8.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/geo-tz/v/8.1.2)
- [GitHub release](https://github.com/evansiroky/node-geo-tz/releases/tag/v8.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: